### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by YotoCoder** [piwneuh/d2api-python#1]
Hello, it doesn't work for me when I invite to the lobby and the client appears disconnected shortly after running the server, what version of python and operating system did you use if it works well for you?

**Comment by piwneuh** [comment]
Hello Yoto, I have moved to using and developing [d2api](https://github.com/piwneuh/d2api/tree/main), it's written in GO and has a http server running alongside steam and dota2 clients. It is fully dockerized as well, so you shouldn't have any problems starting it up.
In case you want a more rudimentary version of the api, with straight forward endpoints checkout [v0](https://github.com/piwneuh/d2api/tree/v0)

**Comment by YotoCoder** [comment]
So do I have to learn GO to be able to do it? :(

**Comment by piwneuh** [comment]
Absolutely not. Just interact with the API endpoints. Currently, scheduling matches and retrieving match data is supported. If you look at the v0 branch, you'll find some simpler endpoints, such as: createLobby, invitePlayer, launchLobby, etc.

**Comment by piwneuh** [comment]
I will proceed with closing this issue and archiving the repository. Thank you for taking an interest.
